---
 
 - hosts: all
   become: true
   pre_tasks:
   - name: install updates (AlmaLinux)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "AlmaLinux"
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
 - hosts: web_servers
   become: true
   tasks:
   - name: install httpd package (AlmaLinux)
     tags: apache,Alma,httpd
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "AlmaLinux"
   - name: install apache2 package (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 - hosts: db_servers
   become: true
   tasks:
   - name: install mariadb server package (AlmaLinux)
     tags: Alma,db,mariadb
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "AlmaLinux"
   - name: install mariadb server
     tags: db,mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
 - hosts: file_servers
   tags: samba
   become: true
   tasks:
   - name: install samba package
     tags: samba
     package:
       name: samba
       state: latest
